### ISSUE TITLE
Note[CategoryId] => Activity[CategoryId]

### ISSUE THREAD

**Issue by samhowes** [samhowes/foothills-data#10]
- [x] Initial data load
- [x] @revsean reviews
- [x] Address feedback

**Comment by samhowes** [comment]
@revsean initial data load complete: 4424 notes processed, at least 3276 uploaded. Looks like there were a few notes skipped because they were not in an included category. Ready for review.

**Comment by revsean** [comment]
Overall we are 90% the way there.

Few edits:

- [ ] Use the API link https://people.planningcenteronline.com/people/AC27642915/notes where the number is their PCO profile ID. 
- [ ] Can we add the name of the person who added the note to the activity title "A Caring Notes Note was added by [[Name]]"
- [ ] Minor, we already have Note in the name of Caring Notes and Pastoral Notes, so it repeated in the activity title 

![Screen Shot 2021-09-16 at 8 24 46 AM](https://user-images.githubusercontent.com/86415336/133629808-84f75546-3a54-4644-8e36-03f63171e0dc.png)


Realizing because we have the custom channels set up, we can split up a few of the note types into their own activity type. Update the google sheet with the categories ID and other information.:

- [ ] Add Caring Kit Activity Type
- [ ] Add Meal Train Activity Type

**Comment by samhowes** [comment]
@revsean Upload is in progress, but the most recent data has been updated, please review for closing:

![image](https://user-images.githubusercontent.com/6216665/133891980-63ef4b4a-99be-46ea-aab2-ae6c4ed8dab4.png)

**Comment by revsean** [comment]
Looks greats!
